### ISSUE TITLE
Keywords and Copyright sitting too high

### ISSUE THREAD

**Issue by MrQuallzin** [chao-master/TSSSFF-Generator#16] opened 2015-06-12 00:04 UTC
Both are sitting too high. Keywords on the official cards are centered in the purple box. Copyright on the official cards is slightly higher than center. This seems to fix itself when using the Experimental Export.
![capture](https://cloud.githubusercontent.com/assets/3629189/8121114/e9e42bea-105b-11e5-80bf-949ddd0b79bf.PNG)

**Comment by chao-master** [comment] 2015-06-12 00:44
Duplicate of #9, Please see that issue for progress

**Closed as completed by chao-master** 2015-06-12 00:44 UTC
